import type { Metadata } from "next";
import { Dancing_Script, Manrope, Poppins, Sora } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
});

const dancingScript = Dancing_Script({
  subsets: ["latin"],
  variable: "--font-dancing-script",
});

export const metadata: Metadata = {
  title: "Portfolio Website",
  description: "Generated by create next app",
  keywords: ["portfolio"],
  authors: [{ name: "Bijay Magar" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${dancingScript.variable}  antialiased`}>{children}</body>
    </html>
  );
}
